# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: '0 14 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-datasets:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Runs a set of commands using the runners shell
    - name: update datasets
      env:
        GHA_DEPLOY_KEY: ${{ secrets.GHA_DEPLOY_KEY }}
      run: |
        ./refresh.sh
        git add .
        git config --local user.email "tip@gha"
        git config --local user.name "GHA"
        git commit -a -m "update datasets"
        git remote set-url origin "$(git config --get remote.origin.url | sed 's#http.*com/#git@github.com:#g')"
        eval `ssh-agent -t 60 -s`
        echo "$GHA_DEPLOY_KEY" | ssh-add -
        mkdir -p ~/.ssh/
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git push origin master
        ssh-agent -k
