# This is a basic workflow to help you get started with Actions

name: Update Datasets

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: '0 22 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-datasets:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
    # Runs a set of commands using the runners shell
    - name: update datasets
      run: |
        ./refresh.sh
    - name: create commit
      run: |
        git config --local user.email "taylor@singlemusic.com"
        git config --local user.name "Taylor O'Connor"
        git commit -m "update datasets" -a
    - name: push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
